INSERT INTO genres (genre_label, genre_name) VALUES 
('action', 'Action'),
('news', 'Actualité'),
('adventure', 'Aventure'),
('animation', 'Animation'),
('biography', 'Biographie'),
('comedy', 'Comédie'),
('short', 'Court métrage'),
('documentary', 'Documentaire'),
('drama', 'Drame'),
('erotica', 'Erotique'),
('experimental', 'Experimentale'),
('family', 'Famille'),
('fantasy', 'Fantasy'),
('film-noir', 'Film-noir'),
('game-show', 'Game-show'),
('history', 'Historique'),
('horror', 'Horreur'),
('music', 'Musique'),
('musical', 'Musical'),
('mystery', 'Mystère'),
('crime', 'Policier'),
('reality-tv', 'TV réalité'),
('romance', 'Romance'),
('sci-fi', 'Science Fiction'),
('lifestyle', 'Sociologie'),
('sport', 'Sport'),
('talk-show', 'Talk-show'),
('thriller', 'Thriller'),
('war', 'Guerre'),
('western', 'Western');